In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [4]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)


0.9722222222222222

In [5]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


0.9925925925925926

In [6]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train) 
rf.score(X_test,y_test)

0.9814814814814815

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf


KFold(n_splits=5, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [9]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=5)

In [11]:
scores_lr=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=2000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [12]:
scores_lr

[0.9277777777777778,
 0.875,
 0.9415041782729805,
 0.9387186629526463,
 0.9080779944289693]

In [13]:
scores_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [14]:
scores_rf

[0.925,
 0.9111111111111111,
 0.958217270194986,
 0.958217270194986,
 0.9331476323119777]

In [15]:
from sklearn.model_selection import cross_val_score


In [16]:
cross_val_score(LogisticRegression(max_iter=2000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [17]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=60
                                       ),digits.data,digits.target)

array([0.92222222, 0.89166667, 0.95264624, 0.95821727, 0.91364903])